### ISSUE TITLE
Name of the repo

### ISSUE THREAD

**Issue by tjvantoll** [NathanaelA/nativescript-master-technology#1]
Hey @NathanaelA,

First of all this looks great. I’m going to give it a shot later today.

Would you be open to changing the name though? The library seems more like “nativescript-utils” or “nativescript-helpers” rather than “nativescript-master-technology”.

Also getting this on npm would be great too so that it’s easier for others to use 😀

**Comment by NathanaelA** [comment]
@tjvantoll - yep; I have no issues changing the name.   Have no issues sticking it in npm either; but I figured I would get some verification that it is something people wanted.  :grinning:

**Comment by tjvantoll** [comment]
I just gave a few of the DOM-like methods a shot and they seem to work great. Thinking about this more I think that it’s worth having more focused packages for the collection of methods you have here. I’d _love_ to see a nativescript-dom package so that I could do something like this:

``` js
var document = require("nativescript-dom");

exports.loaded = function() {
    document.getElementById("foo").whatever();
};
```

If you’re interested I can help out with some of the documentation and such. We get a lot of requests for a package like this to exist.

**Comment by NathanaelA** [comment]
I totally forgot to follow up on the bug report here for anyone seeing this later.   This was done way back in January; the plugin was split to have more utility features in this library; and all the dom related functions were put into the https://github.com/NathanaelA/nativescript-dom library.
