### ISSUE TITLE
Proposal: use a more graceful way to exit the app on Android

### ISSUE THREAD

**Issue by EddyVerbruggen** [NathanaelA/nativescript-master-technology#10]
Would you take a PR that changed [this line](https://github.com/NathanaelA/nativescript-master-technology/blob/eb7e7ea1cab56ecebee08af6b1d8f7e49a28d14e/master-technology.js#L83) to:

```js
application.android.foregroundActivity.finish()
```

The party trick of the latter is it gracefully exits the app with a transition (slide down on Android 7), whereas the current method kills the app in a bang (suddenly gone, as if it crashed).

**Comment by NathanaelA** [comment]
Yep!   I rarely rarely rarely ever don't use a PR.  ;-)    And I like the idea...

**Comment by NathanaelA** [comment]
PR Accepted.  Thanks.
