### ISSUE TITLE
Process.exit() only minimizes app on Android 7.x

### ISSUE THREAD

**Issue by JorgeHawkins** [NathanaelA/nativescript-master-technology#13]
I'm currently testing my app on newer devices, and I used the `process.exit()` as a handler in the case the app lacks the required permissions for it to work properly. 

However, I noticed that, in Android 7.x (Testing on 7.1.2), the app minimizes when calling `proccess.exit()` instead of closing.

**Comment by NathanaelA** [comment]
This (& other issues) have been fixed in the supported and maintained copy on https://proplugins.org
