### ISSUE TITLE
Reference file is not getting created after installing the plugin

### ISSUE THREAD

**Issue by s-doddapaneni** [NathanaelA/nativescript-master-technology#15]
I don't know if this is a bug from your side or not. I tried in multiple projects and playground as well.

Reference file is not getting created here "./node_modules/nativescript-master-technology/references.d.ts" 

So it says process undefined even if I include /// <reference path="./node_modules/nativescript-master-technology/references.d.ts" /> in my references.d.ts as reference file is not present in the plugin. 

Can I any one know how to fix this ?

**Comment by NathanaelA** [comment]
Well, this is a very early plugin  -- it appears from the code that my plugin does not reference the typings correctly.   That is pretty trivial to fix and I'll try to get a new version that does in the future.  :)
