### ISSUE TITLE
Call "process" not "Process"

### ISSUE THREAD

**Issue by raefa** [NathanaelA/nativescript-master-technology#2]
Very useful little plugin. Thanks for making it!

I note In the readme it refers to:

Process.restart()
Process.exit()
Process.isDebug()
Process.isEmulator()
Process.processMessages()

Should be: 
process.restart()
process.exit()
process.isDebug()
process.isEmulator()
process.processMessages()

**Comment by NathanaelA** [comment]
Good catch -- Thanks!. I'll get that fixed for the next version.
