### ISSUE TITLE
Using with {N}+Angular2 - results in 'undefined is not an object (evaluating 'root.clearImmediate.bind')'

### ISSUE THREAD

**Issue by NathanWalker** [NathanaelA/nativescript-master-technology#5]
Ran into this today trying to use with ShoutOutPlay. This is the order in which I am requiring it with the `main.ts` bootstrap file:

```
// this import should be first in order to load some required settings (like globals and reflect-metadata)
import {nativeScriptBootstrap} from 'nativescript-angular/application';

// nativescript
import {SIDEDRAWER_PROVIDERS} from "nativescript-telerik-ui-pro/sidedrawer/angular";
import {LISTVIEW_PROVIDERS} from 'nativescript-telerik-ui-pro/listview/angular';
import * as app from 'application';
require('nativescript-master-technology');
```

> Jul 31 16:17:05 Mac ShoutOutPlay[19039]: 1   0x1dd482c -[TNSRuntime executeModule:]
> Jul 31 16:17:05 Mac ShoutOutPlay[19039]: 2   0xaebcb main
> Jul 31 16:17:05 Mac ShoutOutPlay[19039]: 3   0x5742a25 start
> Jul 31 16:17:05 Mac ShoutOutPlay[19039]: file:///app/tns_modules/rxjs/util/Immediate.js:11:54: JS ERROR TypeError: undefined is not an object (evaluating 'root.clearImmediate.bind')

Removing the `require('nativescript-master-technology')` fixes so definitely cause by the inclusion of this plugin :(

**Comment by NathanaelA** [comment]
Oh, that is interesting -- Apparently NS-Angular assumes clearImmediate exists; because setImmediate exists.  Not a horrible assumption; but a faulty one in this case.   

I just pushed a new version which should fix this...  :-D
