### ISSUE TITLE
performance.now is not monotonically increasing on iOS

### ISSUE THREAD

**Issue by the-reality-engineer** [NathanaelA/nativescript-master-technology#7]
The current implementation based on `CFAbsoluteTimeGetCurrent()` is incorrect. `performance.now()` should return monotonically increasing time at a high precision (based on an arbitrary reference frame in the near past), not absolute time (which is not monotonically increasing and is not very useful for precise timing).

**Comment by the-reality-engineer** [comment]
I suggest using `CACurrentMediaTime()` or `NSProcessInfo.processInfo.systemUptime` instead.

**Comment by NathanaelA** [comment]
Thanks, I'll check those two calls out.  Do either offer any benefit over the other?

**Comment by the-reality-engineer** [comment]
> Thanks, I'll check those two calls out. Do either offer any benefit over the other?

I'm not sure. There are a handful of options for getting either monotonically increasing time or absolute time, but there doesn't seem to be much information on the differences between the various options within each of those two categories.

**Comment by NathanaelA** [comment]
Doing some googling `CACurrentMediaTime` is a better call.  the other one can also be affected by sleep cycles.   However I'll have to check if this also returns sub-seconds, as second is too large of a resolution for performance.now.  ;-)    At worst case I guess I can use the underlying `mach_absolute_time `

**Comment by NathanaelA** [comment]
Hmm, interesting both are affected by sleeping equally.  So it really depends on which of the two offer better precision, or I'll just have to go to `mach_absolute_time`.

**Comment by the-reality-engineer** [comment]
Yeah, they are both affected by sleep cycles. With most timestamp apis, you either get accurate absolute time or accurate timing, but not both. These apis (CACurrentMediaTime and performance.now()) provide a timestamp that is designed for accurate timing (of relatively short timespans), and should not really be used to determine absolute time or used for timing long-running events, especially between application sessions. When you want to accurately measure performance or make framerate calculations, you care about accurate timing (not accurate time), and if you try to do this with absolute time, arbitrary synchronization adjustments to absolute time can screw up calculations (even going backwards in time). The sleep problem is simple to take care of in practice, as you shouldn't be measuring performance (or doing framerate calculations) when the app is not running.

**Comment by the-reality-engineer** [comment]
Regarding seconds being too large for performance.now, it's fine to convert to milliseconds, as you are doing for android. I don't recommend using `mach_absolute_time`, because although it is monotonically increasing, the units are CPU dependent, so it would be more difficult to convert to milliseconds. Also, I'm not sure but it may also pause when the device is sleeping or whatnot, so (potentially) same "problem" (which as I explained above, isn't really an issue).

**Comment by NathanaelA** [comment]
This is changed in v1.1.0.  :)
