### ISSUE TITLE
Cannot FInd name Process {N}+Angular2

### ISSUE THREAD

**Issue by abalad** [NathanaelA/nativescript-master-technology#8]
`import dialogs = require("ui/dialogs");
import {AuthService} from "./auth.service";
import {Router} from '@angular/router';
require( "nativescript-master-technology" );
`

`
....
 if (result){
                      process.exit();
                    }
....`

**Attempting to execute the TS compiler process method returns the following error**

```
13:34:57 - File change detected. Starting incremental compilation...

app/shared/services/application.service.ts(30,52): error TS2304: Cannot find name 'process'.
```

**Comment by jeffswitzer** [comment]
I also ran into this and manojdcoder's fork seems to fix it. @NathanaelA might want to check out his pull request, I'm also not sure if it's the "correct way" to fix the issue.

**Comment by NathanaelA** [comment]
I'll try and merge this in soon, it just looks like Typings so that TypeScript won't throw any errors because it will now understand the code...

**Comment by umair-ameen** [comment]
Still the same issue.

**Comment by jeffswitzer** [comment]
@NathanWalker one question on this... whenever I `npm install nativescript-master-technology`, `./node_modules/nativescript-master-technology/references.d.ts` doesn't get created. I mean I see it in your GitHub repo, but don't understand why npm doesn't bring it over. Any ideas?

**Comment by NathanaelA** [comment]
@jeffswitzer - You tagged my partner Nathan Walker, not me.  ;-)
But to answer the question this plugin is actually a really old layout (NS 1.x days), I need to upgrade it so that the typings are included in the plugin now, and so that it can be webpacked properly.

**Comment by jeffswitzer** [comment]
@NathanaelA whoops, sorry bout that, and thanks for the explanation.
